#+title: Automated Sql with sqlmap
#+author: gabriel


SQLMap is an open source penetration testing tool that automates the process of detecting and exploiting SQL injection flaws and taking over of database servers.

It comes with a powerful detection engine, many niche features for the ultimate penetration tester and a broad range of switches lasting from database fingerprinting.

documentation ->https://github.com/sqlmapproject/sqlmap/wiki

* Initial usage

BUrp facilitates the process of taking the vulnerable URL, by clicking the right button and copy to file or just copy the text.

Copy to file is the easiest way to do this ->

#+begin_src sh
sqlmap -vv -r request.txt
#+end_src

This will already work, the sqlmap has many more features and methods to do the automated exploration.

#+begin_src sh
sqlmap -vv -r request.txt --dump
#+end_src

SQLMap also works with levels and risk levels, this can be defined with that parameters ->

--level=

--risk=

#+begin_src sh
sqlmap -vv -r request.txt --level=5 --risk=4
#+end_src

             ___
           __H__
  ___ ___[.]_____ ___ ___                  {1.8.4#stable}
     |_ -| . [.]     | .'| . |
 |__  _|_  [,]_|_|_|__,|  _|

      |_|V...       |_|   https://sqlmap.org

Usage: python3 sqlmap [options]
